[package]
name = 'geokit'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.87.0'

[lib]
crate-type = [ 'staticlib' ]
name = 'geokit'

[dependencies]
extendr-api = { version = "*", default-features = false, features = ['result_list'], git = "https://github.com/Yunuuuu/extendr.git", branch = "from_iterator"  }
thiserror = { version = "2.0" }
anyhow = { version = "1.0" }
regex = { version = "1.12" }
memchr = { version = "2.7" }
rayon = { version = "1.11" }
hashbrown = { version = "0.16", default-features = false, features = ['default-hasher'] }
indexmap = { version = "2.13" }
# itertools = { version = "0.14", default-features = false, features = ['use_std'] }
indicatif = { version = "0.18" }
flate2 = { version = "1.1" }
isal-rs = { version = "0.5", optional = true }
pprof = { version = "0.14", features = ["flamegraph"], optional = true }

# remove openssl dependency due to error when loading R package: undefined symbol: EVP_bf_ecb
# enable the system proxy feature and socks5 proxy support: https://docs.rs/reqwest/latest/reqwest/#proxies
# reqwest = { version = '*', default-features = false, features = ['system-proxy', 'socks', 'stream', 'http2', 'rustls-tls'] }

# use tokio stream to download files
# tokio = "*"
# tokio-stream = "*"

[features]
isal = ["dep:isal-rs"] # rename feature `isal-rs` to `isal`

[profile.release]
lto = true
codegen-units = 1
